### ISSUE TITLE
Create Maven releases

### ISSUE THREAD

**Issue by kruton** [str4d/ed25519-java#12]
There is already a `pom.xml`, but it appears no Maven repo releases have been made. Other projects have started copying the source directly into their projects thereby creating a situation where any security problems will persist for a long time since each copy will have to be tracked down and updated.

If this is not the authoritative repository for this code anymore, please point to it in the `README.md`.

**Comment by str4d** [comment]
This is the authoritative repository for the code, but I hadn't decided on how best to make it portable. Back when I was looking into it, setting up a Security Provider was a lot of overhead and problematic regarding signing, but shipping this code in a .jar as-is didn't seem like the right way. But if a .jar without a Provider is sufficient for most people, I can get that published.

**Comment by kruton** [comment]
If you can recall any details, I may be able to help with `Provider` implementation. However, it's useful as-is without the `Provider`.

**Comment by str4d** [comment]
Okay, now that I have the latest patches in, time to install Maven and figure out how to build/upload releases with it :P

**Comment by str4d** [comment]
I have performed a snapshot deployment:

https://oss.sonatype.org/content/repositories/snapshots/net/i2p/crypto/eddsa/

@kruton could you please verify this is working for you?

**Comment by str4d** [comment]
@jawi I would also appreciate your input, to ensure the generated files are suitable for your intended purpose :smile:

**Comment by jawi** [comment]
@str4d I've done some testing in an OSGi environment and your snapshot works fine. I think you're good to go.

**Comment by kruton** [comment]
Yes, it looks good to me.

**Comment by str4d** [comment]
Release for v0.1.0 has been pushed! Waiting to see it in the repository...

**Comment by str4d** [comment]
And it's live! https://search.maven.org/#artifactdetails|net.i2p.crypto|eddsa|0.1.0|bundle

Thanks all for the testing and prodding ;)
