### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [str4d/ed25519-java#16]
Hi
The following source files are without license headers:
./src/net/i2p/crypto/eddsa/EdDSAEngine.java
./src/net/i2p/crypto/eddsa/EdDSAKey.java
./src/net/i2p/crypto/eddsa/EdDSAPrivateKey.java
./src/net/i2p/crypto/eddsa/EdDSAPublicKey.java
./src/net/i2p/crypto/eddsa/KeyFactory.java
./src/net/i2p/crypto/eddsa/KeyPairGenerator.java
./src/net/i2p/crypto/eddsa/Utils.java
./src/net/i2p/crypto/eddsa/math/Constants.java
./src/net/i2p/crypto/eddsa/math/Curve.java
./src/net/i2p/crypto/eddsa/math/Encoding.java
./src/net/i2p/crypto/eddsa/math/Field.java
./src/net/i2p/crypto/eddsa/math/FieldElement.java
./src/net/i2p/crypto/eddsa/math/GroupElement.java
./src/net/i2p/crypto/eddsa/math/ScalarOps.java
./src/net/i2p/crypto/eddsa/math/bigint/BigIntegerFieldElement.java
./src/net/i2p/crypto/eddsa/math/bigint/BigIntegerLittleEndianEncoding.java
./src/net/i2p/crypto/eddsa/math/bigint/BigIntegerScalarOps.java
./src/net/i2p/crypto/eddsa/math/ed25519/Ed25519FieldElement.java
./src/net/i2p/crypto/eddsa/math/ed25519/Ed25519LittleEndianEncoding.java
./src/net/i2p/crypto/eddsa/math/ed25519/Ed25519ScalarOps.java
./src/net/i2p/crypto/eddsa/spec/EdDSAGenParameterSpec.java
./src/net/i2p/crypto/eddsa/spec/EdDSANamedCurveSpec.java
./src/net/i2p/crypto/eddsa/spec/EdDSANamedCurveTable.java
./src/net/i2p/crypto/eddsa/spec/EdDSAParameterSpec.java
./src/net/i2p/crypto/eddsa/spec/EdDSAPrivateKeySpec.java
./src/net/i2p/crypto/eddsa/spec/EdDSAPublicKeySpec.java

./test/net/i2p/crypto/eddsa/Ed25519TestVectors.java
./test/net/i2p/crypto/eddsa/EdDSAEngineTest.java
./test/net/i2p/crypto/eddsa/UtilsTest.java
./test/net/i2p/crypto/eddsa/math/ConstantsTest.java
./test/net/i2p/crypto/eddsa/math/GroupElementTest.java
./test/net/i2p/crypto/eddsa/math/MathUtils.java
./test/net/i2p/crypto/eddsa/math/PrecomputationTestVectors.java
./test/net/i2p/crypto/eddsa/math/bigint/BigIntegerScalarOpsTest.java
./test/net/i2p/crypto/eddsa/math/ed25519/Ed25519FieldElementTest.java
./test/net/i2p/crypto/eddsa/math/ed25519/Ed25519LittleEndianEncodingTest.java
./test/net/i2p/crypto/eddsa/math/ed25519/Ed25519ScalarOpsTest.java
./test/net/i2p/crypto/eddsa/spec/EdDSAPrivateKeySpecTest.java

Please, add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification
Thanks in advance
Regards

**Comment by str4d** [comment]
@puntogil hopefully this satisfies your needs 😃
