### ISSUE TITLE
Fix malformed JavaDoc comments

### ISSUE THREAD

**Issue by str4d** [str4d/ed25519-java#26]
See https://github.com/str4d/ed25519-java/pull/19#discussion_r91150205

**Comment by str4d** [comment]
Using maven-javadoc-plugin 2.9.1 and Java 1.8.0_111, I do not get any errors (with `failOnError=true`). @lgoldstein what Java version did you have the errors with?

**Comment by str4d** [comment]
(As it is, I'm working on resolving this by migrating all equations to LaTeX and using MathJaX for rendering, which will make the equations much more readable for general viewing (but may make them somewhat less readable in IDE tooltips...)

**Comment by lgoldstein** [comment]
I am using Java 1.8.0_112 on Windows 10.

**Comment by str4d** [comment]
@lgoldstein could you please test #27 and see whether that resolves the errors you were having?
