### ISSUE TITLE
Publish a new release?

### ISSUE THREAD

**Issue by ivmaykov** [str4d/ed25519-java#29]
Is it possible to get a new release sometime soon (once master is passing tests etc)? The last (and only) release was almost a year ago. Thanks!

**Comment by str4d** [comment]
I plan on making a new release soon (hopefully once #22 is merged, but that is blocking on discussion with the Curdle WG).

**Comment by ivmaykov** [comment]
If you could also wait for #31, that would be awesome :)

**Comment by lgoldstein** [comment]
Hi,

A few weeks back it was published that ed25519-java has released version 0.1.1 and indeed I was able to pull it from Maven central. However, a few days ago it vanished - can you shed some light on it ?

Thanks

**Comment by str4d** [comment]
@lgoldstein no, I have no idea what that might have been. I certainly haven't made a release recently (that I remember at least - but if I had, it would have been checked in, and the version has only just been incremented from 0.1.0 to 0.2.0-SNAPSHOT). Do you still have a copy of it cached?

**Comment by lgoldstein** [comment]
Sorry, no - I inadvertently deleted it as part of some trial I was running trying to ascertain something and did not back it up. Anyway, it looked like a genuine 0.1.1 release - I even made the necessary adjustments to the SSHD project - see [SSHD-727](https://issues.apache.org/jira/browse/SSHD-727). In any case, any plans to release a version sometime soon (e.g., 1-2 weeks) - I would hate to revert the change...

**Comment by str4d** [comment]
This is unusual, to say the least. Do you recall where you saw the release published?

**Comment by lgoldstein** [comment]
Sorry, I wish I did not delete the release so we would have more information...

**Comment by str4d** [comment]
I've checked JCenter (which pulls from Maven Central), and it doesn't have a 0.1.1 either. IDK whether it pulls *deletions*, but it seems unlikely that the same bug would affect both of them...

In any case, I hope to be making a release in the next few weeks, pending getting some testing of the library - I'll publish a snapshot as soon as I get #22 merged, which should be this weekend.

**Comment by lgoldstein** [comment]
Please keep me informed - thanks...

**Comment by lgoldstein** [comment]
P.S. since you bumped the version to 0.2 please update the value in the `EdDSASecurityProvider` constructor accordingly

**Comment by ivmaykov** [comment]
Any updates on this?

**Comment by lgoldstein** [comment]
We at the [MINA SSHD Project](https://github.com/apache/mina-sshd) are also waiting for it for some time now...

**Comment by str4d** [comment]
I now have enough response from the Curdle WG to know how to proceed with #22, so I will finish and merge that on Friday and cut a new release this weekend :smiley:

**Comment by str4d** [comment]
Release is out! It should appear on Maven Central in the next few hours. @ivmaykov @lgoldstein thanks for your patience 😃

**Comment by lgoldstein** [comment]
Where is it ? It has not appeared yet anywhere...

**Comment by str4d** [comment]
For reference, the release is here: https://search.maven.org/#artifactdetails%7Cnet.i2p.crypto%7Ceddsa%7C0.2.0%7Cbundle

**Comment by lgoldstein** [comment]
Found it - thanks, don't know why it escaped me when I looked for it. In any case, it is now supported by MINA SSHD as a 3rd party security provider.
