### ISSUE TITLE
Clarify contract for accessing curves in EdDSANamedCurveTable

### ISSUE THREAD

**Issue by sappenin** [str4d/ed25519-java#43]
This is a minor nit request, but would it be possible for `EdDSANamedCurveTable` to clarify its contract for accessing the ED_25519 curve spec (and other curves when implemented)?  

One option would be to simply publish a `static final String` constant somewhere that defines the "name" of supported curves.  That would at least allow the library to specify the `String` to pass-in to `getByName`.  As it stands for ed25519, I keep having to define this in various projects that use this lib, which is somewhat error-prone.  Additionally, this contract seems to have changed between `0.1.0` and `0.2.0` (which is fine - the version changed, but it's currently a bit awkward/error-prone to access the curve).

For example, the following would be trivial to add to `EdDSANamedCurveTable`:

```
public class EdDSANamedCurveTable {
   public static final String ED_25519 = "Ed25519";
       ... // rest of this class...
}
```

That would allow me to just do this:

```
final EdDSANamedCurveSpec edParams = EdDSANamedCurveTable.getByName(ED_25519);
```

However, a more preferable mechanism would be to make `EdDSANamedCurveTable` aware of some of its curves.  For example, perhaps there should be a helper method like this in `EdDSANamedCurveTable`:

```
public static EdDSANamedCurveSpec ed25519() {
    return curves.get(ED_25519);
}
```

**Comment by str4d** [comment]
Hmm, I used to do this, but simplified things by removing the constant when I corrected all the names (before adding the Provider). If it makes things simpler for you though, I can certainly add the constant back.

**Comment by str4d** [comment]
>  Additionally, this contract seems to have changed between `0.1.0` and `0.2.0` (which is fine - the version changed, but it's currently a bit awkward/error-prone to access the curve).

To expand on this: in 0.1.0 I used the canonical name `ed25519-sha-512` based on what I could figure out about JCA naming conventions, and aliased that to `Ed25519`. I later realised that this was a) misleading (because Ed25519 would actually be `edwards25519-sha-512` if specified in "full"), and b) conflicted with recently-published RFCs which indicate the canonical name should be `Ed25519`. Thus it made sense to fix things prior to introducing the security Provider in 0.2.0 (at which point the names could be used in APIs I have no control over, and therefore would need to maintain backwards-compatibility for).

**Comment by str4d** [comment]
As a side note, the current contract for accessing Ed25519 in `EdDSANamedCurveTable` is that the latter is case-insensitive, so the curve can be accessed via:

- `Ed25519`
- `ed25519`
- `ED25519`

**Comment by str4d** [comment]
> However, a more preferable mechanism would be to make `EdDSANamedCurveTable` aware of some of its curves. For example, perhaps there should be a helper method like this in `EdDSANamedCurveTable`:

I think I'd prefer to have helpers like that in a separate package (e.g. `net.i2p.crypto.eddsa.helpers`), along with more intuitive signing and verifying methods that wrap the JCA functions.

**Comment by sappenin** [comment]
No objections from my side - I was mostly wanting to avoid the accidental typo where I do something like this in code:

```
EdDSANamedCurveSpec edParams = EdDSANamedCurveTable.getByName("Ed255199");
```
