### ISSUE TITLE
cannot identify EdDSA public key: class net.i2p.crypto.eddsa.EdDSAPublicKey

### ISSUE THREAD

**Issue by simao** [str4d/ed25519-java#44]
When using `EdDSASecurityProvider` I get unexpected errors when running my tests. The first test run always succeeds but subsequent runs always fail with strange errors like:

 `cannot identify EdDSA public key: class net.i2p.crypto.eddsa.EdDSAPublicKey`

A asked about a more detailed example on [stackoverflow](https://stackoverflow.com/questions/44822228/pattern-matching-fails-on-second-try).

I am using other jce providers and this only seems to happen with `EdDSASecurityProvider`. Is there something specific that this provider is doing that might cause this?

Thanks

**Comment by str4d** [comment]
Looking at the SO question and answer, my initial guess is that `EdDSASecurityProvider` is somehow persisting the classloader of the first execution, while `sbt` is setting up a new one in each run. But I can't think of anywhere in my library that might be doing this. Could you give an example of another provider you don't have problems with?

**Comment by simao** [comment]
Yes the problem was with the way sbt uses the classloaders for tests. I found out how to get around it. Other providers were working properly due to the way I was running my tests.

Thanks
