### ISSUE TITLE
Utils.hexToBytes() overflows on odd-length inputs

### ISSUE THREAD

**Issue by arajasek** [str4d/ed25519-java#70]
https://github.com/str4d/ed25519-java/blob/master/src/net/i2p/crypto/eddsa/Utils.java#L81

On inputs of odd-length n, this for-loop tries to access the char at index, an error.

**Comment by str4d** [comment]
Good catch! This function is only used on static constants or test vectors, so it's probably best to just throw a `RuntimeError` if the length is not even.
